version: '3.7'

services:
  app:
    image: ghcr.io/bbnavi/cms:staging
    restart: unless-stopped
    networks:
      public:
    environment:
      NUXT_PUBLIC_AUTH_SECRET: ${NUXT_PUBLIC_AUTH_SECRET}
      NUXT_PUBLIC_AUTH_ORIGIN: ${NUXT_PUBLIC_AUTH_ORIGIN}
      NUXT_PUBLIC_AUTH_ENDPOINT: ${NUXT_PUBLIC_AUTH_ENDPOINT}
      NUXT_PUBLIC_USER_ENDPOINT: ${NUXT_PUBLIC_USER_ENDPOINT}
      NUXT_PUBLIC_DATAHUB_ENDPOINT: ${NUXT_PUBLIC_DATAHUB_ENDPOINT}
      NUXT_PUBLIC_GRAPHQL_ENDPOINT: ${NUXT_PUBLIC_GRAPHQL_ENDPOINT}
      NUXT_PUBLIC_GRAPHQL_AUTH_ENDPOINT: ${NUXT_PUBLIC_GRAPHQL_AUTH_ENDPOINT}
    command: yarn start
    deploy:
      labels:
        traefik.enable: "true"
        traefik.port: 3000
        traefik.docker.network: public
        traefik.main.frontend.rule: Host:preview.cms.bbnavi.de

networks:
  public:
    external: true
