query ($id: ID!) {
  newsItem (id: $id) {
    visible
    categories {
      id
      name
    }
    id
    author
    fullVersion
    charactersToBeShown
    publicationDate
    publishedAt
    title
    externalId
    sourceUrl {
      url
      description
    }
    address {
      addition
      street
      zip
      city
      geoLocation {
        latitude
        longitude
      }
    }
    dataProvider {
      name
      contact {
        firstName
        lastName
        phone
        fax
        email
        webUrls {
          url
          description
        }
      }
      address {
        addition
        street
        zip
        city
        geoLocation {
          latitude
          longitude
        }
      }
      logo {
        url
        description
      }
    }
    contentBlocks {
      title
      intro
      body
      mediaContents {
        id
        captionText
        contentType
        copyright
        height
        width
        sourceUrl {
          url
          description
        }
      }
    }
    pushNotificationsSentAt
  }
}
