name: Docker Image CI
on:
  push:
    branches: [ epam/* ]

jobs:
  prep:
    runs-on: ubuntu-latest
    environment: epam-staging
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: git.bbnavi.vk256.eu
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - id: docker_build
      uses: docker/build-push-action@v2
      with:
        build-args: |
          NUXT_PUBLIC_AUTH_SECRET=${{ secrets.NUXT_PUBLIC_AUTH_SECRET }}
          NUXT_PUBLIC_AUTH_ORIGIN=${{ secrets.NUXT_PUBLIC_AUTH_ORIGIN }}
          NUXT_PUBLIC_AUTH_ENDPOINT=${{ secrets.NUXT_PUBLIC_AUTH_ENDPOINT }}
          NUXT_PUBLIC_USER_ENDPOINT=${{ secrets.NUXT_PUBLIC_USER_ENDPOINT }}
          NUXT_PUBLIC_GRAPHQL_ENDPOINT=${{ secrets.NUXT_PUBLIC_GRAPHQL_ENDPOINT }}
          NUXT_PUBLIC_GRAPHQL_AUTH_ENDPOINT=${{ secrets.NUXT_PUBLIC_GRAPHQL_AUTH_ENDPOINT }}
        push: true
        tags: git.bbnavi.vk256.eu/bbnavi/cms:latest

